### ISSUE TITLE
Extract table of ipyrad stats file 9-sep

### ISSUE THREAD

**Issue by cristoichkov** [cristoichkov/GBS_Bioinf_Process_Mamm#17]
#### ipyrad creates folders with different out files, for example, *.phy* and *.vcf*. Also generates one file with all *the statistics summary*. This file contains several tables and I want to extract one of these. 
Example:
[stats.txt](https://github.com/cristoichkov/GBS_Bioinf_Process_Mamm/blob/master/out/ipyrad_outfiles/parameters/clust_82_80_outfiles/clust_82_80_stats.txt)
#### But.. I'm trying to standardize parameters in ipyrad, so I have several folders for the results of each parameter.  
Example:
[ipyrad outfiles folders](https://github.com/cristoichkov/GBS_Bioinf_Process_Mamm/tree/master/out/ipyrad_outfiles/parameters)

#### My goal is to extract the tables for each parameter and put all in a file, and paste the name of the parameter in the first column. 

Example:
[final file](https://github.com/cristoichkov/GBS_Bioinf_Process_Mamm/blob/master/out/ipyrad_outfiles/stats/Example_file.txt)

#### With this script I can extract the number of loci of each file using the `awk` command and paste the name of the parameter in the first column. 

```
#!/bin/bash

## Obtein the total of snp and loci for each parameter, and create a table
for i in `ls -d -- ../out/ipyrad_outfiles/parameters/* | grep "_outfiles" | sed "s/..\/out\/ipyrad_outfiles\/parameters\///" | sed "s/_outfiles//"
`; do  # Create a list of the names of all output folder
  cd ../out/ipyrad_outfiles/parameters/${i}_outfiles  # Enter to each output folder
  for k in `awk '{if(NR==14) print $0}' ${i}_stats.txt | grep -Eo "[0-9]{1,10}" | awk '{if(NR==3) print $0}'`; do # Search the loci number obtained
    for p in `head -n 1 ${i}.snps.phy | cut -sd " " -f 2`; do  # Search the snps number obtained
    echo ${i} ${k} ${p} >> ../../stats/param_clust.txt # Show the parameter, the number of loci and SNPs, and put the result in a txt file
  done
  done
  cd ../../../../bin
done
```

Example:
[ipyrad parameters](https://github.com/cristoichkov/GBS_Bioinf_Process_Mamm/blob/master/out/ipyrad_outfiles/stats/param_clust.txt)

### But I don't know how to extract a complete table !!

**Comment by AliciaMstt** [comment]
This seems like this question on stacksoverflow [R: Read in csv, find first line matching pattern](https://stackoverflow.com/questions/19013423/r-read-in-csv-find-first-line-matching-pattern)

That's my tip.

Make sure your solution includes an R function with the relevant arguments to be reused with different number of samples etc.

**Comment by VeroIarrachtai** [comment]
Hi all, the command for this case is :

```{r}
# Assuming that what indicates the
#  start of param2 is the follwing line
param2.indic <- "## Final Sample stats summary"


# read in the raw file
lines <- readLines("clust_82_80_outfiles/clust_82_80_stats.txt")

# find the start of parameter 2
p2.start <- grep(param2.indic, lines)

# go down n+2 lines from p2.start
n <- 1:75  # which line to find
lines[p2.start + n + 1]
```

Now, we need do function ;)

**Comment by AliciaMstt** [comment]
I recommend using `read.table()` instead of `lines[]` because this way it would be easier to get the table in a dataframe (rows and columns instead of everything in a single column, as `readLines()` does. Also, notice that ipyrad separates columns by a different number of spaces, that is [why in this case `read.table()` is a better idea than `read.delim()`](https://stackoverflow.com/questions/16979858/reading-text-file-with-multiple-space-as-delimiter-in-r).

**Comment by cristoichkov** [comment]
Hii!! I'm working in the loop 

```
source(ipyrad_extract_table.R)

df_stats <- data.frame()
for (i in folders){
  name <- stringr::str_extract(string = i, pattern = "clust_[0-9]+_[0-9]+")
  tab <- extract_table(paste0("../out/ipyrad_outfiles/parameters/", i, "/", name, "_stats.txt"), "## Final Sample stats summary")
  df_stats <- rbind(df_stats, tab)
}

```

**Comment by LauraMCE** [comment]
Hi!! I added the file for the function in R to extract the summary table that you want, @cristoichkov ([ipyrad_extract_table.r](https://github.com/cristoichkov/GBS_Bioinf_Process_Mamm/blob/master/bin/ipyrad_extract_table.r)). It is now in your repo.

**Comment by AliciaMstt** [comment]
Great done team! My only comment to `ipyrad_extract_table.r` is that in its documentation it would be useful to add more details on what type of ipyrad output this functions works with. For instance the output of which program/command of ipyread.

**Comment by cristoichkov** [comment]
### Hi everybody!!
I checked the ipyrad files and saw that the stat.txt file is the only one with multiple tables. The other files only contain one table and I think is easier to obtain. Therefore my function is designed only for the stats.txt file. Also, I modified the function because it didn't work with the other tables inside of stats.txt file. Because 3 tables match with the number of samples, but the others no. 

Now you can use it!!
[ipyrad_extract_table.R](https://github.com/cristoichkov/GBS_Bioinf_Process_Mamm/blob/master/bin/ipyrad_extract_table.R)

I'm still working in the loop of above

**Comment by cristoichkov** [comment]
I finished the loop to concatenate all the tables and added the identifier of each parameter analyzed

```
## Call the function ipyrad_extract_table
source("ipyrad_extract_table.R")

## List the directories 
folders <- list.files("../out/ipyrad_outfiles/parameters")

## Create a dataframe empty
df_stats <- data.frame()

for (i in folders){
  
  ## Since the directories end in _outfiles we have to stay alone with the folder identifier in this case clust_ [0-9]+_ [0-9]+
  name <- stringr::str_extract(string = i, pattern = "clust_[0-9]+_[0-9]+")
  
  ## Extract the desired table, for this we use paste0 to enter the folders where are the stats.txt files
  tab <- ipyrad_extract_table(paste0("../out/ipyrad_outfiles/parameters/", i, "/", name, "_stats.txt"), 5, 74)
  
  ## Create a dataframe repeating the identifier according to with the number of row of the table 
  param <- data.frame(rep(name, times = nrow(tab)))
  
  ## Change the name of identifier column
  colnames(param) <- "param"
  
  ## combine the data frames by columns
  final <- cbind(param, tab)
  
  ## combine the data frames by rows
  df_stats <- rbind(df_stats, final)
}
```
Check to see if I made a mistake and know if the function and the loop are well explained.

See you later!!
