### ISSUE TITLE
Fix paths to bin

### ISSUE THREAD

**Issue by AliciaMstt** [cristoichkov/GBS_Bioinf_Process_Mamm#24]
Your scripts hetero_s5_consens.r, ipyrad_param_stats.r, plot_mean_bootstrap.r (and maybe others, check).

have a line at the beginning of the sript that says: `setwd("~/GBS_Bioinf_Process_Mamm/bin")`

Please notice that this will prevent your script working in any computer, if GBS_Bioinf_Process_Mamm is not in home. Also, remember that by default the working directory of any script will be the directory where it is saved, which in this case is `/bin`. Therefore setting your wd to bin is unnecessary. In other words, you can delete the `setwd` line from all your scripts.

**Comment by cristoichkov** [comment]
I deleted all the setwd("~/GBS_Bioinf_Process_Mamm/bin") of my scripts. Fixed it! 

Thanks for your advice.
