### ISSUE TITLE
How to get the genetic distance between individuals of the same sampling location

### ISSUE THREAD

**Issue by cristoichkov** [cristoichkov/GBS_Bioinf_Process_Mamm#25]
Mastretta-Yanes et al. (2014) recommended choosing the parameters that minimize the genetic distance between individuals from the same locality.

![Captura de pantalla de 2019-11-13 15-42-36](https://user-images.githubusercontent.com/38633482/68807695-e5633300-062d-11ea-95b9-0d5bbb62ac56.png)

I have the results in vcf format, I tried to do it in R, but I couldn't did it. 

I have followed this process.

1.- read the vcf file in R. (vcfR and adegenet)
2.- Define the population 
3.- Obtain the genetic distance (What distance? nei?)
4.- Boxplot with the population and genetic distance.

But I don't know if I am correct.

Help Me!!

**Comment by tono2204** [comment]
Hello Chris, 

You can use the command line ``` vcftools --vcf clust_82_80.vcf --plink --out clust_82_80 ```  (https://stackoverflow.com/questions/39671015/how-to-convert-vcf-file-to-ped-file-using-plink) to convert from vcf to plink (map and ped files).

**Comment by tono2204** [comment]
Vero says that you will need a fam file so you can edit it (first column) with the names of each sample.  The following command line will help you: ```./plink --file clust_82_80  --make-bed --out clust_82_80 ```
You will have 3 output files : .bed, .bim, and .fam.
Then, you can try and convert your file to vcf again: 
```
./plink --file clust_82_80 --recode vcf --out clust_82_80

```

**Comment by cristoichkov** [comment]
This is the name of my vcf
clust_82_80.vcf

**Comment by tono2204** [comment]
The ```--recodeAD``` option saves the data to a single file: plink.raw

**Comment by almamelisa** [comment]
Here is the link to indicated the population 

https://ipyrad.readthedocs.io/en/latest/6-params.html#pop-assign-file

**Comment by cristoichkov** [comment]
Hi Everybody!! Thanks for your help, I found the answer using your advice and I created a script to did it. I leave the code in case anyone needs it.

[Script to get the genetic distances a plot them](https://github.com/cristoichkov/GBS_Bioinf_Process_Mamm/blob/master/bin/genetic_distance.r)

![Genetic_dist_mindepth](https://user-images.githubusercontent.com/38633482/69213403-9cc5e100-0b29-11ea-89ad-55ac7ae76a8d.png)
